# Generated by Django 4.2.4 on 2023-08-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
