# Generated by Django 4.2.4 on 2023-08-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_custom_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='is_super_user',
            new_name='is_superuser',
        ),
    ]
