# Generated by Django 4.2.4 on 2023-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_is_super_user_custom_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
