# Generated by Django 4.2.4 on 2023-08-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_custom_user_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='img',
        ),
    ]
